# Generated by Django 4.2.5 on 2024-02-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
