# Generated by Django 5.0.2 on 2024-03-01 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='author',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 55, 11, 874942)),
        ),
    ]
