# Generated by Django 5.0.2 on 2024-03-01 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(default='admin', max_length=50)),
                ('starttime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 12, 18, 2, 213210))),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
