# Generated by Django 5.0.2 on 2024-03-01 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_starttime_accessmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 13, 52, 42, 805456)),
        ),
    ]
