# Generated by Django 5.0.2 on 2024-03-02 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_group_count_productmodel_max_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 12, 5, 34, 337892)),
        ),
    ]
